[package]
name = "syndeebar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.16.2"
gtk-layer-shell = "0.5.1"
tokio = { version = "1.25.0", features = ["full"] }
